const Data = [
  {
    Name: "Brimstone",
    Nationality: "USA",
    Role: "Controller",
    id: 1,
  },
  {
    Name: "Phoenix",
    Nationality: "UK",
    Role: "Duelist",
    id: 2,
  },
  {
    Name: "Sage",
    Nationality: "China",
    Role: "Sentinel",
    id: 3,
  },
  {
    Name: "Sova",
    Nationality: "Russia",
    Role: "Initiator",
    id: 4,
  },
  {
    Name: "Viper",
    Nationality: "USA",
    Role: "Controller",
    id: 5,
  },
  {
    Name: "Cypher",
    Nationality: "Morocco",
    Role: "Sentinel",
    id: 6,
  },
  {
    Name: "Reyna",
    Nationality: "Mexico",
    Role: "Duelist",
    id: 7,
  },
  {
    Name: "Killjoy",
    Nationality: "Germany",
    Role: "Sentinel",
    id: 8,
  },
  {
    Name: "Breach",
    Nationality: "Sweden",
    Role: "Initiator",
    id: 9,
  },
  {
    Name: "Omen",
    Nationality: "unknown",
    Role: "Controller",
    id: 10,
  },
  {
    Name: "Jett",
    Nationality: "South Korea",
    Role: "Duelist",
    id: 11,
  },
  {
    Name: "Raze",
    Nationality: "Brazil",
    Role: "Duelist",
    id: 12,
  },
  {
    Name: "Skye",
    Nationality: "Australia",
    Role: "Initiator",
    id: 13,
  },
  {
    Name: "Yoru",
    Nationality: "Japan",
    Role: "Duelist",
    id: 14,
  },
  {
    Name: "Astra",
    Nationality: "Ghana",
    Role: "Controller",
    id: 15,
  },
  {
    Name: "Kay/O",
    Nationality: "unknown",
    Role: "Initiator",
    id: 16,
  },
  {
    Name: "Chamber",
    Nationality: "France",
    Role: "Sentinel",
    id: 17,
  },
  {
    Name: "Neon",
    Nationality: "Philippines",
    Role: "Duelist",
    id: 18,
  },
  {
    Name: "Fade",
    Nationality: "Turkey",
    Role: "Initiator",
    id: 19,
  },
  {
    Name: "Harbor",
    Nationality: "India",
    Role: "Controller",
    id: 20,
  },
  {
    Name: "Gekko",
    Nationality: "USA",
    Role: "Initiator",
    id: 21,
  },
];

export default Data;
